version: '3.7'

services:

  php:
#    build:
#      context: ./dockerfiles
#      dockerfile: php_dockerfile
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ./:/app
    ports:
      - 8000:80
    container_name: "${PROJECT_NAME}_php"
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_php.rule=Host(`${PROJECT_BASE_URL}`)"

  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    container_name: "${PROJECT_NAME}_mysql"
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intranet
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock