export const ACTIVE_USERS = 'chat/ACTIVE_USERS';
export const GET_CONTACTS = 'chat/GET_CONTACTS';
export const SET_UNREAD_MESSAGES = 'chat/SET_UNREAD_MESSAGES';
export const TOGGLE_WORKING_STATUS = 'chat/TOGGLE_WORKING_STATUS';
export const SET_SELECTED_CONTACT = 'chat/SET_SELECTED_CONTACT';